name: subzerov2
services:
  - name: subzero-md-service
    type: web
    ports:
      - 3000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    env:
      - OWNERS=263719647303;❣️Mr Frank
      - MODE=public
      - PREFIX="."
      - antidelete=false
      - ANTI_LINK=false
      - AUTOREAD=false
      - VIEWONCE=false
      - STATUS_REPLY=false
      - STATUSLIKES=true
      - STATUS_MSG="SubZero Md View Your Status"
      - BOT_NAME=PRINCE-MD
      - PACK_NAME="SUBZERO V2🚀"
      - DL_MSG="_📥-------- *DOWNLOADED SUCCESSFULLY* --------📥_"
      - STATUSVIEW=false
      - Status_Saver=false
      - REJECTSCALLS=false
      - AutoReaction=false
      - SESSION_ID="" # Add your session ID here
    regions:
      - fra
      - sin
